[package]
name = "slidebuf"
version = "0.0.1"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Very basic sliding buffer"

[lib]
doctest = false

[dependencies]
bytes = "1.5.0"
